# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-07 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
