# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-08 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0002_auto_20161207_2130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lineup',
            unique_together=set([('zipcode', 'provider')]),
        ),
    ]
